backend/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("django.contrib.auth.urls")),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', include('tranz.urls', namespace='tranz')),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/tranz/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    FigurantViewSet,
    TransactionViewSet,
    FigurantList,
    FigurantCreate, FigurantUpdate,
    convertator, network_analysis, global_search,
    create_chart, generate_reports,
    procurement_pivot, procurement_download, procurement_update
)
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static
from django.conf import settings

app_name = 'tranz'

router = DefaultRouter()
router.register(r'figurant', FigurantViewSet)
router.register(r'transaction', TransactionViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('tranz/', login_required(FigurantList.as_view(), login_url='/'), name='figurant_list'),
    path('create/', login_required(FigurantCreate.as_view(), login_url='/'), name='create_figurant'),
    path('update/<str:pk>/', login_required(FigurantUpdate.as_view(), login_url='/'), name='update_figurant'),
    path('generate_reports/<str:pk>/', generate_reports, name='generate_reports'),
    path('create_chart/<str:pk>/', create_chart, name='create_chart'),
    path('procurement_download/<str:pk>/', procurement_download, name='procurement_download'),
    path('procurement_pivot/<str:pk>/', procurement_pivot, name='procurement_pivot'),
    path('procurement_update/<str:pk>/', procurement_update, name='procurement_update'),
    path('convertator/', convertator, name='convertator'),
    path('global_search/', global_search, name='global_search'),
    path('network_analysis/', network_analysis, name='network_analysis'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += router.urls

backend/tranz/models.py
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings
from django_ckeditor_5.fields import CKEditor5Field
import os

# Create your models here.
class Figurant(models.Model):
    STATUS_CHOICES = [
                    ('-', '-'),
                    ('У роботі', 'У роботі'),
                    ('Відпрацьовано', 'Відпрацьовано'),
                    ('Кошик', 'Кошик')
                    ]
 
    fig_inn = models.CharField(primary_key=True, max_length=50)
    fig_name = models.TextField()
    activity_info = CKEditor5Field(null=True, blank=True, config_name="extends")
    add_info = CKEditor5Field(null=True, blank=True, config_name="extends")
    fig_logo = models.ImageField(default="fallback.png", blank=True, upload_to=f'logos/')
    status = models.CharField(choices=STATUS_CHOICES, default="-")
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if self.fig_logo:
            if not os.path.exists(os.path.join(settings.MEDIA_ROOT, 'logos')):
                os.makedirs(os.path.join(settings.MEDIA_ROOT, 'logos'))
            file_name = os.path.basename(self.fig_logo.name)
            if "logo" not in file_name and file_name != 'fallback.png':
                file_base, file_extension = os.path.splitext(file_name)
                file_base = self.fig_inn
                
                #
                figurant_inn_dir = os.path.join(settings.MEDIA_ROOT, 'logos', self.fig_inn)
                
                if not os.path.exists(figurant_inn_dir):
                    os.makedirs(figurant_inn_dir)
                
                #
                logo_files_count = len([name for name in os.listdir(figurant_inn_dir) if os.path.isfile(os.path.join(figurant_inn_dir, name))])
                
                self.fig_logo.name = os.path.join(f'{file_base}', f"logo_{logo_files_count + 1}_" + file_base + file_extension)

        super(Figurant, self).save(*args, **kwargs)

    def __str__(self):
        return f"Назва: {self.fig_name} (ІНН {self.fig_inn})"

class FigAccount(models.Model):
    figurant = models.ForeignKey(
        Figurant, on_delete=models.CASCADE
        )
    account = models.TextField(null=True)
    currency = models.TextField(null=True)
    bank_code = models.TextField(null=True)
    bank_name = models.TextField(null=True)
    
    def __str__(self):
        return f"{self.figurant}, номер рахунку: {self.account}"
    
class Transaction(models.Model):    
    fig_acc = models.ForeignKey(
        FigAccount, on_delete=models.CASCADE
        )
    contr_acc=models.TextField(null=True)
    contr_name=models.TextField(null=True)
    contr_ipn=models.TextField(null=True)
    contr_bank_code=models.TextField(null=True)
    contr_bank_name=models.TextField(null=True)
    pay_purp=models.TextField(null=True)
    doc_num=models.TextField(null=True)
    doc_date=models.DateTimeField(null=True)
    direction=models.TextField(null=True)
    sum_ct=models.FloatField(null=True)
    sum_dt=models.FloatField(null=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.fig}, транзакції рахунку: {self.fig_acc}"

backend/tranz/forms.py
from typing import Any, Mapping
from django import forms
from django.forms import inlineformset_factory, modelformset_factory

from .models import (
    Figurant,
    FigAccount,
    Transaction
)

from django.utils.translation import gettext_lazy as _

class FigurantForm(forms.ModelForm):

    class Meta:
        model = Figurant
        fields = '__all__'
        labels = {
            "fig_inn": "Код фігуранта",
            "fig_name": "Назва фігуранта",
            "activity_info": "Діяльність",
            "add_info": "Додаткова інформація",
            "fig_logo": "Фото/лого фігуранта",
            "status": "Статус",
        }
       
        widgets = {
            'fig_inn': forms.TextInput(
                attrs={
                    'class': 'form-control'
                    }
                ),
            'fig_name': forms.TextInput(
                attrs={
                    'class': 'form-control'
                    }
                ),
        }

class FigAccForm(forms.ModelForm):

    class Meta:
        model = FigAccount
        fields = '__all__'
        labels = {
            "account": "Рахунок",
            "currency": "Валюта",
            "bank_code": "Код банку",
            "bank_name": "Назва банку",
        }
       
        widgets = {
            'account': forms.TextInput(
                attrs={
                    'class': 'form-control'
                    }
                ),
            'currency': forms.TextInput(
                attrs={
                    'class': 'form-control'
                    }
                ),
            'bank_code': forms.TextInput(
                attrs={
                    'class': 'form-control'
                    }
                ),
            'bank_name': forms.TextInput(
                attrs={
                    'class': 'form-control'
                    }
                ),
        }

class TransactionForm(forms.ModelForm):

    class Meta:
        model = Transaction
        fields = '__all__'
        labels = {
            "contr_acc": "07. Контрагент_Рахунок",
            "contr_name": "08. Контрагент_ПІБ",
            "contr_ipn": "09. Контрагент_ІПН",
            "contr_bank_code": "10. Контрагент_Код банку",
            "contr_bank_name": "11. Контрагент_Найменування банку",
            "pay_purp": "12. Призначення платежу",
            "doc_num": "13. Номер документа",
            "doc_date": "14. Дата документа",
            "direction": "15. Напрямок",
            "sum_ct": "16. Сумма операції Кт",
            "sum_dt": "17. Сумма операції Дт",
        }

FigurantFormSet = modelformset_factory(
    Figurant, fields=('fig_inn', 'fig_name'),
    extra=1, can_delete=True)

FigAccFormSet = inlineformset_factory(
    Figurant, FigAccount, form=TransactionForm,
    extra=1, can_delete=True,
    can_delete_extra=True
)

TransactionFormSet = inlineformset_factory(
    FigAccount, Transaction, form=FigAccForm,
    extra=1, can_delete=True,
    can_delete_extra=True
)

backend/tranz/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, View
from django.http import JsonResponse, HttpResponse
from django.conf import settings
from .filters import FigurantFilter
from datetime import datetime, timezone, timedelta
import os
import pandas as pd
from io import BytesIO
from rest_framework import viewsets
from .serializers import FigurantSerializer, TransactionSerializer
import traceback

from .forms import (
                    FigurantForm,
                    TransactionFormSet
                    )

from .models import (
                    Figurant,
                    FigAccount,
                    Transaction,
                    )

class FigurantViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Figurant.objects.all()
    serializer_class = FigurantSerializer

class TransactionViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Transaction.objects.all()
    serializer_class = TransactionSerializer

class FigurantList(ListView):
    model = Figurant
    template_name = "tranz/figurant_list.html"
    context_object_name = "figurants"

    def get_queryset(self):
        queryset = Figurant.objects.all()
        status = self.request.GET.get('status')
        if status:
            if status == 'total':
                queryset = queryset
            elif status == 'in_progress':
                queryset = queryset.filter(status='У роботі')
            elif status == 'done':
                queryset = queryset.filter(status='Відпрацьовано')
            elif status == 'basket':
                queryset = queryset.filter(status='Кошик')
        self.filterset = FigurantFilter(self.request.GET, queryset=queryset)
        filtered_queryset = self.filterset.qs
        return filtered_queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = Figurant.objects.all()
        
        myFilter = FigurantFilter(self.request.GET, queryset=queryset)
        filtered_queryset = myFilter.qs
        
        context['total_figurants'] = filtered_queryset.count()
        context['progress_figurants'] = filtered_queryset.filter(status='У роботі').count()
        context['done_figurants'] = filtered_queryset.filter(status='Відпрацьовано').count()
        context['basket_figurants'] = filtered_queryset.filter(status='Кошик').count()
        context['myFilter'] = myFilter
        
        return context

class FigurantInline():
    form_class = FigurantForm
    model = Figurant
    template_name = "tranz/figurant_create_or_update.html"

    def form_valid(self, form):
        form.instance.uploaded_by = self.request.user
        named_formsets = self.get_named_formsets()

        self.object = form.save()

        for name, formset in named_formsets.items():
            formset_save_func = getattr(self, 'formset_{0}_valid'.format(name), None)
            if formset_save_func is not None:
                formset_save_func(formset)
            else:
                formset.save()
        
        formatted_time = datetime.now(timezone(timedelta(hours=3))).strftime('%d.%m.%Y %H:%M:%S')
        messages.success(self.request, f'Дані збережені успішно. Час збереження: {formatted_time}')
        
        return redirect('tranz:update_figurant', pk=form.instance.pk)

    def formset_transactions_valid(self, formset):
        """
        Hook for custom formset saving.. useful if you have multiple formsets
        """
        transactions = formset.save(commit=False)
        for obj in formset.deleted_objects:
            obj.delete()
        for transaction in transactions:
            transaction.figurant = self.object
            transaction.save()

class FigurantCreate(FigurantInline, CreateView):

    def get_context_data(self, **kwargs):
        ctx = super(FigurantCreate, self).get_context_data(**kwargs)
        ctx['named_formsets'] = self.get_named_formsets()
        return ctx

    def get_named_formsets(self):
        if self.request.method == "GET":
            return {
                'transactions': TransactionFormSet(prefix='transactions'),
            }
        else:
            return {
                'transactions': TransactionFormSet(self.request.POST or None, self.request.FILES or None, prefix='transactions'),
            }

class FigurantUpdate(FigurantInline, UpdateView):

    def get_context_data(self, **kwargs):
        ctx = super(FigurantUpdate, self).get_context_data(**kwargs)
        ctx['named_formsets'] = self.get_named_formsets()
        return ctx

    def get_named_formsets(self):
        fig_account = FigAccount.objects.filter(figurant=self.object).first() 
        return {
            'transactions': TransactionFormSet(
                self.request.POST or None,
                self.request.FILES or None,
                instance=fig_account,
                prefix='transactions'
            ),
        }

def convertator(request):
    if request.method == 'POST' and request.FILES.getlist('files'):
        file_type = request.POST.get('file_type')
        uploaded_files = request.FILES.getlist('files')
        combined_data = []

        try:
            for uploaded_file in uploaded_files:
                save_path = os.path.join(settings.MEDIA_ROOT, 'sayari', uploaded_file.name)

                if not uploaded_file.name.endswith('.csv'):
                    return render(request, 'products/convertator.html', {
                        'error': f"{uploaded_file.name} не формату CSV з системи Sayari",
                    })
                
                #
                os.makedirs(os.path.dirname(save_path), exist_ok=True)

                #
                with open(save_path, 'wb+') as destination:
                    for chunk in uploaded_file.chunks():
                        destination.write(chunk)
                
                try:
                    df = pd.read_csv(save_path, delimiter=',')
                except:
                    df = pd.read_csv(save_path, delimiter=';')

                df['arrival_date'] = df['arrival_date'].str.replace('[', '', regex=False).str.replace(']', '', regex=False).str.replace('"', '', regex=False).str.replace("'", '', regex=False)

                combined_data.append(df)

            combined_df = pd.concat(combined_data, ignore_index=True)

            if file_type == 'Excel':
                buffer = BytesIO()
                with pd.ExcelWriter(buffer, engine='openpyxl') as writer:
                    combined_df.to_excel(writer, index=False, sheet_name='Sayari')
                buffer.seek(0)

                response = HttpResponse(
                        buffer,
                        content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
                    )
                current_datetime = datetime.now().strftime("%d-%m-%Y_%H-%M-%S")
                response['Content-Disposition'] = f'attachment; filename="data_sayari_{current_datetime}.xlsx"'
                return response
            
            elif file_type == 'i2':
                return render(request, "tranz/convertator.html", {"error": "Функціонал не працює - у процесі розробки"})

        except Exception as e:
            tb = traceback.format_exc()
            return render(request, 'tranz/convertator.html', {
                'error': f"Помилка {str(uploaded_file)}: {str(tb)}"
            })
    return render(request, 'tranz/convertator.html', {'message': 'Файли успішно опрацьовано'})

def global_search(request):
    return JsonResponse({"message": "У процесі розробки"})

def network_analysis(request):
    return JsonResponse({"message": "У процесі розробки"})

def create_chart(request):
    return JsonResponse({"message": "У процесі розробки"})

def generate_reports(request):
    return JsonResponse({"message": "У процесі розробки"})

def procurement_pivot(request):
    return JsonResponse({"message": "У процесі розробки"})

def procurement_download(request):
    return JsonResponse({"message": "У процесі розробки"})

def procurement_update(request):
    return JsonResponse({"message": "У процесі розробки"})

backend/tranz/templates/tranz/figurant_create_or_update.html
{% extends "base.html" %}

{% block content %}
{% if messages %}
    <div class="container mt-3" style="max-width: 10000px; margin: 0 auto;">
        {% for message in messages %}
            <div 
                class="alert alert-{{ message.tags }} alert-dismissible fade show" 
                role="alert"
            >
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    </div>
{% endif %}

<form enctype="multipart/form-data" class="container" method="post" id="figurant_form" style="max-width: 10000px; margin: 0 auto;">
    {% csrf_token %}

    <!-- main form start --- in our case figurant form -->
    <div class="card">
        <div class="card-header card-header-secondary">
            {% if figurant.fig_inn %}
                <h4 class="card-title d-flex justify-content-center">
                    <a href="{% url 'tranz:create_chart' figurant.fig_inn %}" class="btn custom-btn" style="width: 200px;">
                        Схема
                    </a>
                    <a href="{% url 'tranz:generate_reports' figurant.fig_inn %}" class="btn custom-btn" style="width: 200px;">
                        Довідка
                    </a>
                </h4>
            {% endif %}
        </div>
        
        <!-- add logo -->
        <style>
            .logo {
                display: block;
                max-width: 200px;
                max-height: 200px;
                width: auto;
                height: auto;
                margin: 0 auto;
            }
            .custom-btn {
                background-color: white;
                color: black;
                border: 1px solid black;
                text-align: center;
                font-weight: bold;
                transition: background-color 0.3s ease, color 0.3s ease;
            }
            .custom-btn:hover {
                background-color: black;
                color: white;
            }
        </style>
        <img
            class='logo' 
                src="{{ figurant.fig_logo.url }}"
                alt="{{ figurant.fig_inn.url }}"
             />
        {{ form.media }}
        {{ form.as_p }}
        <style>
            label[for="id_activity_info"],
            label[for="id_add_info"],
            label[for="id_fig_logo"]   {
                                        text-align: center;
                                        font-weight: bold;
                                        color: red;
                                        display: block;
                                        }
        </style>
    </div>

    {% with named_formsets.procurements as formset %}
        <div class="table-responsive card mt-4">
            <div class="card-header card-header-secondary">
                {% if figurant.fig_inn %}
                    <a href="{% url 'tranz:update_figurant' figurant.fig_inn %}" class="btn btn-secondary" style="width: 500px;">
                        Зв'язані транзакції (к-ть {{ formset.initial_form_count }})
                    </a>
                    <a href="{% url 'tranz:procurement_pivot' figurant.fig_inn %}" class="btn custom-btn" style="width: 200px;">Звести</a>
                    <a href="{% url 'tranz:procurement_download' figurant.fig_inn %}" class="btn custom-btn" style="width: 200px;">Завантажити XLSX</a>
                    <a href="{% url 'tranz:procurement_update' figurant.fig_inn %}" class="btn custom-btn" style="width: 200px;">Оновити</a>
                {% else %}
                    <span class="btn btn-secondary disabled" style="width: 500px;">
                        Зв'язані транзакції (к-ть {{ formset.initial_form_count }})
                    </span>
                {% endif %}
            </div>
        </div>
    {% endwith %}

    <br/><br/>

    <div class="form-group">
        <button type="submit" class="btn btn-secondary btn-block">Зберегти</button>
        <a href="{% url 'tranz:figurant_list' %}" class="btn btn-secondary btn-block">Скасувати</a>
    </div>

</form>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        
{% endblock content %}

backend/tranz/templates/tranz/figurant_list.html
{% extends "base.html" %}

{% block content %}
    <div class="card" style="margin: 20px; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
        <div class="card-header card-header-secondary" style="background-color: #ffffff; color: #000000; padding: 15px;">
            <h4 class="card-title" style="margin: 0; font-size: 1.5rem; font-weight: 600; color: #000000; letter-spacing: 1px; text-transform: uppercase; text-align: center;">BANKIR MANAGEMENT SYSTEM</h4>
            {% include 'tranz/status.html' %}
            <div style="margin-top: 10px;">
                <a href="{% url 'tranz:create_figurant' %}" class="animated-link">Додати</a>
                <a> | </a>
                <a href="{% url 'tranz:global_search' %}" class="animated-link">Глобальний пошук</a>
                <a> | </a>
                <a href="{% url 'tranz:network_analysis' %}" class="animated-link">Зв'язки-Схеми-Довідки</a>
                <a> | </a>
                <a href="{% url 'tranz:convertator' %}" class="animated-link">Конвертація</a>
            </div>
        </div>
        
        <div class="row" style="margin: 20px;">
            <div class="col-md">
                <div class="card card-body text-center" style="padding: 20px; border-radius: 8px;">
                    <table class="table table-hover">
                        <thead style="margin: 0; font-size: 1.2rem; font-weight: 600; color: #000000; letter-spacing: 1px; text-transform: uppercase; text-align: center; background-color: #ffffff; color: #000000;">
                            <tr>
                                <th>Код</th>
                                <th>Назва</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for figurant in figurants %}
                                <tr style="cursor: pointer;">
                                    <td><a href="{% url 'tranz:update_figurant' figurant.fig_inn %}" fig="_blank" style="color: black; text-decoration: none;">{{ figurant.fig_inn }}</a></td>
                                    <td><a href="{% url 'tranz:update_figurant' figurant.fig_inn %}" fig="_blank" style="color: black; text-decoration: none;">{{ figurant.fig_name }}</a></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>    
    </div>

    <style>
        .animated-link {
            color: black;
            text-decoration: none;
            margin-right: 15px;
            padding: 5px 10px;
            border-radius: 4px;
            transition: all 0.3s ease;
        }

        .animated-link:hover {
            background-color: black;
            color: #ffffff;
            transform: scale(1.1);
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        }
        
        .table {
            border-collapse: collapse;
            width: 100%;
            margin: 20px 0;
            border: 1px solid #ddd;
        }

        .table th, .table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: center;
        }

        .table th {
            background-color: #f9f9f9;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 1px;
        }

        .table-hover tbody tr:hover {
            background-color: #f1f1f1;
            cursor: pointer;
        }

    </style>
{% endblock content %}

backend/tranz/templates/tranz/status.html
<br>
<div class="row">
    <div class="col">
        <div class="col-md">
            <div class="top-card text-center text-white bg-success mb-3" id="figurants-total" data-status="total" onclick="filterFigurants('total')">
                <div class="card-header">
                    <h5 class="card-title">Всі</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{total_figurants}}</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="col-md">
            <div class="top-card text-center text-white bg-primary mb-3" id="figurants-progress" data-status="in_progress" onclick="filterFigurants('in_progress')">
                <div class="card-header">
                    <h5 class="card-title">У роботі</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{progress_figurants}}</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="col-md">
            <div class="top-card text-center text-black mb-3" id="figurants-delivered" data-status="done" onclick="filterFigurants('done')">
                <div class="card-header">
                    <h5 class="card-title">Відпрацьовані</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{done_figurants}}</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="col-md">
            <div class="top-card text-center text-white bg-danger mb-3" id="basket" data-status="basket" onclick="filterFigurants('basket')">
                <div class="card-header">
                    <h5 class="card-title">Кошик</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{basket_figurants}}</h3>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    .top-card:hover {
        transform: scale(1.2);
        cursor: pointer;
    }
</style>

<script>
    function filterFigurants(status) {
        const url = new URL(window.location.href);
        url.searchParams.set('status', status);
        window.location.href = url.toString();
    }
</script>